version: "3.8"

services:
    n8n:
        image: gokulthedon/docker_n8n:latest
        container_name: n8n
        restart: always

        ports:
            - "5678:5678" # Change host port if 5678 is busy

        environment:
            - N8N_HOST=localhost
            - N8N_PORT=5678
            - N8N_PROTOCOL=http

            # Very Important - Security
            - N8N_ENCRYPTION_KEY=PL_iAZSSdVTJm0feLE<&mClH]|PsDN6W

            # Optional but Recommended
            - N8N_EDITOR_BASE_URL=http://localhost:5678
            - WEBHOOK_URL=http://localhost:5678/

            # Timezone
            - TZ=Asia/Kolkata

        volumes:
            - n8n_data:/home/node/.n8n

volumes:
    n8n_data:
